#!/bin/bash
# Test runners menu - shows available test options

echo "═══════════════════════════════════════════════════════"
echo "TS-EDASM - Test Runner Options"
echo "═══════════════════════════════════════════════════════"
echo ""
echo "QUICK START:"
echo "  bash test.sh                # Basic test with logging"
echo "  bash run-all-tests.sh       # Complete test suite"
echo ""
echo "DETAILED OPTIONS:"
echo "  bash quick-test.sh          # Fast validation"
echo "  bash run_test_debug.sh      # Detailed with system info"
echo "  bash run-tests.sh [cat]     # Categorized tests"
echo ""
echo "TEST CATEGORIES (for run-tests.sh):"
echo "  all                  # All tests (default)"
echo "  golden               # Golden tests (byte verification)"
echo "  integration          # Integration tests (fixtures)"
echo "  smoke                # Smoke tests (basic checks)"
echo "  coverage             # All tests with coverage"
echo "  watch                # Watch mode"
echo ""
echo "CUSTOM RUNNERS:"
echo "  node test-runner.js         # Node.js test runner"
echo "  npx vitest verify-fixes.test.ts  # Verification tests"
echo ""
echo "VIEW LOGS:"
echo "  bash view-logs.sh           # Show available logs"
echo "  cat test_logs/*.log         # View specific log"
echo "  tail -50 test_logs/*.log    # View last 50 lines"
echo ""
echo "SEARCH LOGS:"
echo "  grep FAIL test_logs/*.log   # Find failures"
echo "  grep -i error test_logs/*.log # Find errors"
echo ""
echo "═══════════════════════════════════════════════════════"
echo ""
echo "Log files are saved to: test_logs/"
echo "Each run creates a new timestamped log file"
echo ""
